stages:
  stage_01:
    cmd: python stage_01.py
    deps:
      - stage_01.py
    outs:
      - artifacts_1.txt
  
  stage_02:
    cmd: python stage_02.py
    deps:
      - artifacts_1.txt
      - stage_02.py
    outs:
      - artifacts_2.txt