stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  
  split_data:
    cmd: python src/stage_02_train_test_split.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_train_test_split.py
      - src/utils/all_utils.py
      - config/config.yaml
      - params.yaml
      - artifacts/raw_local_dir/data.csv
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
  
  training_model:
    cmd: python src/stage_03_training.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_training.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
    params:
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio
      - base.random_state
    outs:
      - artifacts/model_dir/ElasticNet_v1.model
  
  evaluating_model:
    cmd: python src/stage_04_evaluation.py --config=config/config.yaml
    deps:
      - src/stage_04_evaluation.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/ElasticNet_v1.model
    outs:
      - artifacts/scores_dir/scores.json