name: cicd-ml-use-case

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run:  |
          # Your ML workflow commands
          pip install --upgrade pip
          pip install -r requirements.txt

          dvc repro -v ## v >>> verbose

          echo " # Reports" >> report.md
          echo "## metrics" >> report.md
          cat artifacts/scores_dir/scores.json >> report.md

          cml-send-comment report.md



